### ISSUE TITLE
奇怪，真机无法弹出

### ISSUE THREAD

**Issue by bxcx** [JerryFans/JFPopup#3]
JFPopupView.popup.actionSheet { [self] in
            [
                JFPopupAction(with: "xxx", subTitle: nil, clickActionCallBack: {
                }),

                JFPopupAction(with: "xxx", subTitle: nil, clickActionCallBack: {
                }),
            ]
        }

用了上面的代码，在模拟器上完全正常，但在真机上无法弹出，请问会是什么问题呢？

**Comment by JerryFans** [comment]
是我的example还是你集成的代码？真机iOS版本多少，Xcode 版本多少

**Comment by bxcx** [comment]
xcode Version 14.0.1，真机13.6，
使用 JFPopupView.popup 无法展示 actionSheet、dialog、toast这些都没有，但有事件日志输出，只是显示不出来。
但在ViewController中换成 self.popup 可以展示，难道不能使用静态的 JFPopupView.popup 来控制吗，静态的会方便许多

**Comment by JerryFans** [comment]
> xcode Version 14.0.1，真机13.6，
> 使用 JFPopupView.popup 无法展示 actionSheet、dialog、toast这些都没有，但有事件日志输出，只是显示不出来。
> 但在ViewController中换成 self.popup 可以展示，难道不能使用静态的 JFPopupView.popup 来控制吗，静态的会方便许多

你的问题我没法重现，但是我在1.5.2尝试修复了你的问题， 你可以试试看，没问题的话我就close掉 @bxcx
