### ISSUE TITLE
建议弹窗消失增加回调

### ISSUE THREAD

**Issue by KeepCoding9494** [JerryFans/JFPopup#4]
enableDrag设置未false dialog类型的弹窗还是可以通过滑动手势自动消失掉，我把源码里的tap和pan手势全部注释依然可以通过滑动手势取消掉弹窗  8P 15.4系统

**Comment by JerryFans** [comment]
不好意思最近比较忙，我看了下代码，enableDrag是控制bottomSheet能不能往下滑动收起的，如果你想dialog类型点击背景不消失请设置isDismissible = false, 这个参数默认是true
