### ISSUE TITLE
发现loading框有时不会消失

### ISSUE THREAD

**Issue by neworiginou** [JerryFans/JFPopup#5]
大佬你好，因为业务需要 有时可能会需要连续展示loading  这时发现了hideloading不掉的场景，忘修复
伪代码：
           JFPopupView.popup.loading()
            delay(time: 1.0) {//模拟异步请求
                JFPopupView.popup.hideLoading()
                JFPopupView.popup.loading(hit: "请求中")
                delay(time: 2.6) {
                    JFPopupView.popup.hideLoading()
                    JFPopupView.popup.toast(hit: "请求成功")
                }
            }

**Comment by JerryFans** [comment]
> 大佬你好，因为业务需要 有时可能会需要连续展示loading 这时发现了hideloading不掉的场景，忘修复
> 伪代码：
> JFPopupView.popup.loading()
> delay(time: 1.0) {//模拟异步请求
> JFPopupView.popup.hideLoading()
> JFPopupView.popup.loading(hit: "请求中")
> delay(time: 2.6) {
> JFPopupView.popup.hideLoading()
> JFPopupView.popup.toast(hit: "请求成功")
> }
> }

这段测试代码 会重现是么？ 好的 我有时间处理下

**Comment by neworiginou** [comment]
> > 大佬你好，因为业务需要 有时可能会需要连续展示loading 这时发现了hideloading不掉的场景，忘修复
> > 伪代码：
> > JFPopupView.popup.loading()
> > delay(time: 1.0) {//模拟异步请求
> > JFPopupView.popup.hideLoading()
> > JFPopupView.popup.loading(hit: "请求中")
> > delay(time: 2.6) {
> > JFPopupView.popup.hideLoading()
> > JFPopupView.popup.toast(hit: "请求成功")
> > }
> > }
> 
> 这段测试代码 会重现是么？ 好的 我有时间处理下

会重现的 看了下源码 没找到啥地方出了问题 忘指教

**Comment by JerryFans** [comment]
V1.5.3 已修复。 已上传到Pod 稍后可指定最新版本 重新pod install --repo-update即可

**Comment by neworiginou** [comment]
好的 大佬，这里bug产生的原因是不是 JFToastView文件里的 config.enableAutoDismiss这句代码 是不是

**Comment by JerryFans** [comment]
> 好的 大佬，这里bug产生的原因是不是 JFToastView文件里的 config.enableAutoDismiss这句代码 是不是

不完全是 现在修改后 跟这个参数没关系了  同一时间只会存在一个LoadingView(或者enableAutoDismiss = false的自定义View)。这种View是手动调用方法销毁的 同一时间只能存在一个。
