### ISSUE TITLE
新手求教，直接扔到podfile里，下载不下来，还需要什么配置么

### ISSUE THREAD

**Issue by hanxiaofeng** [JerryFans/JFPopup#8]
<img width="820" alt="image" src="https://github.com/JerryFans/JFPopup/assets/10582931/4837abda-9c98-478e-977c-1db97f8b8f77">

<img width="890" alt="image" src="https://github.com/JerryFans/JFPopup/assets/10582931/02704474-1116-4174-acae-45cd5cde1c92">

**Comment by JerryFans** [comment]
看提示 让你用这个命令 pod install --repo-update， 你的本地repo没更新 自然没有

**Comment by JerryFans** [comment]
> @JerryFans 我的pod版本是1.12.1，是不是太老了，刚刚没指定版本，自动下载了1.5.3版本的库

这个应该没太大关系 我的比你还低。 主要看你本地仓库。 那你可以指定版本 如果没问题的话
